BC-10512: following files has been updated:
- .github/*: updated scripts for staging test split in manual and main workflow
- package.json: added basic script to run for all workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,11 +18,15 @@ on:
         description: "tag for running cypress tests"
         type: string
       environment:
-        description: "environment for retriving credentials from 1Password vault"
+        description: "environment for retrieving credentials from 1Password vault"
         type: string
       groups:
         description: "identifier to store test results, reports, and artifacts separately, preventing overwrites in parallel runs."
         type: string
+      browser:
+        description: "browser to run tests in"
+        type: string
+        default: "edge"
 
 jobs:
   configure-load-secrets-and-run_tests:
@@ -75,25 +79,27 @@ jobs:
           working-directory: e2e-system-tests
           command: npm run pretest
 
-      - name: Start Edge (Headless)
-        run: |
-          nohup microsoft-edge-stable --headless --no-sandbox &
-          echo $! > edge_pid
+      # - name: Start Edge (Headless)
+      #   run: |
+      #     nohup microsoft-edge-stable --headless --no-sandbox &
+      #     echo $! > edge_pid
 
       - name: Cypress run
         uses: cypress-io/github-action@v6
         with:
           working-directory: e2e-system-tests
-          command: npm run ${{ inputs.tag }}
-          browser: edge
+          command: npm run cy:headless:stable:ci --
+            --env tags="@stable_test and ${{ inputs.tag }} and ${{ inputs.groups }}",
+            parallelGroup=${{ inputs.groups }}
+          browser: ${{ inputs.browser }}
 
-      - name: Clean Up Edge Process
-        if: always()
-        run: |
-          if [ -f edge_pid ]; then
-            kill $(cat edge_pid) || true
-            rm edge_pid
-          fi
+      # - name: Clean Up Edge Process
+      #   if: always()
+      #   run: |
+      #     if [ -f edge_pid ]; then
+      #       kill $(cat edge_pid) || true
+      #       rm edge_pid
+      #     fi
 
       - name: Generate Report
         if: always()
